### ISSUE TITLE
Add set m_collideConnected for joint

### ISSUE THREAD

**Issue by Ughuuu** [erincatto/box2c#88]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] Ask for help on [discord](https://discord.gg/NKYgCBP) and/or [reddit](https://www.reddit.com/r/box2d)
- [ ] Consider providing a dump file using b2World::Dump

**Comment by ShockSlayer** [comment]
Seconded!

**Comment by erincatto** [comment]
Do you change this after creation? What is the game scenario?

**Comment by ShockSlayer** [comment]
I had just noticed that out of all of the jointDefs, only the b2MotorJointDef didn't have a collideConnected parameter anymore, which seemed odd, since it still requires specifying two bodies. I also didn't realize that this issue was about having a setter after creation, I thought it was about the def. Not a problem for me yet since I haven't come up with a gameplay reason to have this, and it's not an option in v2.4, so no migration issues. That said, if the OP has a gameplay reason I'd be curious to hear it too.

**Comment by Ughuuu** [comment]
I am simulating a softbody, eg butter, and i use the flag to make the softbody more soft(eg frozen butter vs melted butter)

**Comment by erincatto** [comment]
Implemented.
 
![image](https://github.com/erincatto/box2c/assets/7284063/d1226bf7-a8bc-412a-adc9-35a333a20228)
![image](https://github.com/erincatto/box2c/assets/7284063/9445d6db-582b-42de-bf58-ba4f14ee300d)

**Comment by Ughuuu** [comment]
Yess, thanks!
